//import javafx.stage.FileChooser;
//
//import javax.swing.*;
//import javax.swing.filechooser.FileNameExtensionFilter;
//import javax.xml.soap.Text;
//import java.awt.*;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.awt.event.WindowEvent;
//import java.awt.event.WindowListener;
//import java.beans.PropertyChangeListener;
//import java.io.*;
//import java.nio.charset.Charset;
//import java.nio.file.Files;
//import java.util.Arrays;
//import java.util.concurrent.Executor;
//
///**
// * @author Viston
// */
//
//public class GUI extends javax.swing.JFrame implements ActionListener {
//
//    /**
//     * Creates new form vCLIBuilder
//     */
//
//    public static void main(String[] args) {
//        SwingUtilities.invokeLater(new Runnable() {
//            public void run() {
//                GUI gui = new GUI();
//                JFrame frame = new JFrame();
//                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                frame.setContentPane(gui.getContentPane());
//                frame.setTitle("vCLIBuilder - By Viston");
//                frame.pack();
//                frame.setVisible(true);
//            }
//        });
//    }
//    
//    public GUI() {
//        initComponents();
//        CreateOpenFile();
//        ChooseOsbot();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        createFileBtn = new javax.swing.JButton();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        jLabel6 = new javax.swing.JLabel();
//        jLabel7 = new javax.swing.JLabel();
//        jLabel8 = new javax.swing.JLabel();
//        Debug = new javax.swing.JTextField();
//        osbotUserName = new javax.swing.JTextField();
//        osbotPassword = new javax.swing.JTextField();
//        rsUserName = new javax.swing.JTextField();
//        rsPassword = new javax.swing.JTextField();
//        scriptName = new javax.swing.JTextField();
//        scriptParams = new javax.swing.JTextField();
//        world = new javax.swing.JTextField();
//        openFileBtn = new javax.swing.JButton();
//        osbotJarBtn = new javax.swing.JButton();
//
//        createFileBtn.setText("SAVE");
//
//        jLabel1.setText("Debug Option:");
//
//        jLabel2.setText("OSBot Username:");
//
//        jLabel3.setText("OSBot Password:");
//
//        jLabel4.setText("Runescape Username:");
//
//        jLabel5.setText("Runescape Password:");
//
//        jLabel6.setText("Script Name/ID:");
//
//        jLabel7.setText("Params:");
//
//        jLabel8.setText("World:");
//
//        scriptName.setToolTipText("");
//
//        openFileBtn.setText("OPEN");
//
//        osbotJarBtn.setText("OSBOT Jar");
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                                        .addGroup(layout.createSequentialGroup()
//                                                                .addComponent(jLabel5)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(rsPassword))
//                                                        .addGroup(layout.createSequentialGroup()
//                                                                .addComponent(jLabel3)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(osbotPassword))
//                                                        .addGroup(layout.createSequentialGroup()
//                                                                .addComponent(jLabel4)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(rsUserName))
//                                                        .addGroup(layout.createSequentialGroup()
//                                                                .addComponent(jLabel2)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(osbotUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                                .addGap(70, 70, 70)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                                        .addGroup(layout.createSequentialGroup()
//                                                                .addComponent(jLabel1)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(Debug))
//                                                        .addGroup(layout.createSequentialGroup()
//                                                                .addComponent(jLabel8)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(world))
//                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                                                .addComponent(jLabel7)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(scriptParams))
//                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                                                .addComponent(jLabel6)
//                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                                .addComponent(scriptName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addComponent(osbotJarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(openFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(createFileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap(36, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                .addGap(24, 24, 24)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jLabel6)
//                                                        .addComponent(scriptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jLabel7)
//                                                        .addComponent(scriptParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jLabel8)
//                                                        .addComponent(world, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jLabel1)
//                                                        .addComponent(Debug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jLabel2)
//                                                        .addComponent(osbotUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jLabel3)
//                                                        .addComponent(osbotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jLabel4)
//                                                        .addComponent(rsUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                        .addComponent(jLabel5)
//                                                        .addComponent(rsPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                                .addGap(29, 29, 29)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(createFileBtn)
//                                        .addComponent(openFileBtn)
//                                        .addComponent(osbotJarBtn))
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>
//
//    // Variables declaration - do not modify
//    private String osbotJar;
//    private javax.swing.JTextField Debug;
//    private javax.swing.JButton createFileBtn;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JButton openFileBtn;
//    private javax.swing.JButton osbotJarBtn;
//    private javax.swing.JTextField osbotPassword;
//    private javax.swing.JTextField osbotUserName;
//    private javax.swing.JTextField rsPassword;
//    private javax.swing.JTextField rsUserName;
//    private javax.swing.JTextField scriptName;
//    private javax.swing.JTextField scriptParams;
//    private javax.swing.JTextField world;
//    // End of variables declaration
//
//    public void ChooseOsbot() {
//        JFileChooser fc = new JFileChooser();
//        fc.setCurrentDirectory(new File("C:\\Users\\Viston\\Desktop"));
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Jar File", "jar");
//        fc.setFileFilter(filter);
//        fc.setDialogTitle("Choose your OSBot File");
//
//        osbotJarBtn.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                if (fc.showOpenDialog(osbotJarBtn) == JFileChooser.APPROVE_OPTION) {
//                    osbotJar = fc.getSelectedFile().getName();
//                }
//            }
//        });
//    }
//
//    public void CreateOpenFile() {
//        JFileChooser fc = new JFileChooser();
//        fc.setCurrentDirectory(new File("C:\\Users\\Viston\\Desktop"));
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("BAT File", "bat");
//
//        fc.setFileFilter(filter);
//        fc.setDialogTitle("Choose File Directory");
//
//
//        createFileBtn.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                if (!osbotUserName.getText().trim().isEmpty() && !osbotPassword.getText().trim().isEmpty() && !rsUserName.getText().trim().isEmpty() && !rsPassword.getText().trim().isEmpty() && !scriptName.getText().trim().isEmpty()) {
//                    if (osbotJar != null) {
//                        if (fc.showSaveDialog(createFileBtn) == JFileChooser.APPROVE_OPTION) {
//                            try (FileWriter fw = new FileWriter(fc.getSelectedFile() + ".bat")) {
//                                fw.write(osbotJar + " -login " + osbotUserName.getText() + ":" + osbotPassword.getText() + " -bot " + rsUserName.getText() + ":" + rsPassword.getText() + ":" + "0000 -script "
//                                        + scriptName.getText() + ":" + scriptParams.getText());
//                            } catch (IOException e1) {
//                                e1.printStackTrace();
//                            }
//                            System.out.println("Created File: " + fc.getSelectedFile().getAbsolutePath());
//                        }
//                    } else {
//                        JOptionPane.showMessageDialog(osbotJarBtn, "Please select your Jar file!");
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(createFileBtn, "You have missed one or more necessary fields!");
//                }
//            }
//
//        });
//
//        openFileBtn.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                if (fc.showOpenDialog(openFileBtn) == JFileChooser.APPROVE_OPTION) {
//                    File cliFile = new File(fc.getSelectedFile().getAbsolutePath());
//                    ProcessBuilder startBat = new ProcessBuilder("cmd.exe", "/C", cliFile.getAbsolutePath());
//                    File fcDirectory = fc.getCurrentDirectory();
//                    startBat.directory(fcDirectory);
//                    try {
//                        startBat.start();
//                    } catch (IOException e1) {
//                        e1.printStackTrace();
//                    }
//                }
//            }
//        });
//    }
//
//    @Override
//    public void actionPerformed(ActionEvent e) {
//
//    }
//}